# Generated by Django 5.0.2 on 2024-06-18 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(blank=True, choices=[('Pabna Express', 'Pabna Express'), ('Banglabandha Express', 'Banglabandha Express'), ('Chattala Express', 'Chattala Express')], default=None, max_length=150, null=True)),
                ('ticket_type', models.CharField(blank=True, choices=[('Economy', 'Economy'), ('Royal', 'Royal'), ('Business', 'Business')], default=None, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('destination', models.CharField(blank=True, choices=[('Dhaka to Borishal', 'Dhaka to Borishal'), ('Pabna to Dhaka', 'Pabna to Dhaka'), ('Borishal to Dhaka', 'Borishal to Dhaka'), ('Dhaka to Pabna', 'Dhaka to Pabna')], default=None, max_length=200, null=True)),
                ('coach', models.IntegerField(blank=True, choices=[(4, 4), (5, 5), (3, 3), (2, 2), (6, 6), (1, 1)], default=None, null=True)),
                ('phone_no', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('sit_no', models.IntegerField(blank=True, choices=[(8, 8), (17, 17), (20, 20), (13, 13), (18, 18), (2, 2), (11, 11), (4, 4), (14, 14), (5, 5), (7, 7), (16, 16), (9, 9), (1, 1), (10, 10), (19, 19), (12, 12), (3, 3), (6, 6), (15, 15)], default=None, null=True)),
                ('trip_no', models.IntegerField(blank=True, default=1000000, null=True, unique=True)),
                ('already_booking', models.BooleanField(blank=True, default=None, null=True)),
                ('finish_trip', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
