# Generated by Django 5.0.2 on 2024-06-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='already_booking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='destination',
            field=models.CharField(blank=True, choices=[('Dhaka to Pabna', 'Dhaka to Pabna'), ('Pabna to Dhaka', 'Pabna to Dhaka'), ('Borishal to Dhaka', 'Borishal to Dhaka'), ('Dhaka to Borishal', 'Dhaka to Borishal')], default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Economy', 'Economy'), ('Royal', 'Royal')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='train_name',
            field=models.CharField(blank=True, choices=[('Chattala Express', 'Chattala Express'), ('Pabna Express', 'Pabna Express'), ('Banglabandha Express', 'Banglabandha Express')], default=None, max_length=150, null=True),
        ),
    ]
