# Generated by Django 5.0.2 on 2024-06-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_alter_ticketbooking_already_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='coach',
            field=models.IntegerField(blank=True, choices=[(3, '3'), (6, '6'), (2, '2'), (5, '5'), (4, '4'), (1, '1')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='destination',
            field=models.CharField(blank=True, choices=[('Dhaka to Borishal', 'Dhaka to Borishal'), ('Dhaka to Pabna', 'Dhaka to Pabna'), ('Pabna to Dhaka', 'Pabna to Dhaka'), ('Borishal to Dhaka', 'Borishal to Dhaka')], default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='sit_no',
            field=models.IntegerField(blank=True, choices=[(16, '16'), (3, '3'), (13, '13'), (12, '12'), (15, '15'), (10, '10'), (19, '19'), (18, '18'), (2, '2'), (4, '4'), (11, '11'), (20, '20'), (8, '8'), (5, '5'), (14, '14'), (1, '1'), (7, '7'), (6, '6'), (9, '9'), (17, '17')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('Royal', 'Royal'), ('Economy', 'Economy'), ('Business', 'Business')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='train_name',
            field=models.CharField(blank=True, choices=[('Pabna Express', 'Pabna Express'), ('Chattala Express', 'Chattala Express'), ('Banglabandha Express', 'Banglabandha Express')], default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='trip_no',
            field=models.IntegerField(blank=True, default=1000000, null=True),
        ),
    ]
