# Generated by Django 5.0.2 on 2024-06-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_alter_ticketbooking_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='coach',
            field=models.IntegerField(blank=True, choices=[(6, '6'), (3, '3'), (1, '1'), (5, '5'), (4, '4'), (2, '2')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='destination',
            field=models.CharField(blank=True, choices=[('Borishal to Dhaka', 'Borishal to Dhaka'), ('Pabna to Dhaka', 'Pabna to Dhaka'), ('Dhaka to Pabna', 'Dhaka to Pabna'), ('Dhaka to Borishal', 'Dhaka to Borishal')], default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='sit_no',
            field=models.IntegerField(blank=True, choices=[(12, '12'), (16, '16'), (10, '10'), (18, '18'), (6, '6'), (3, '3'), (1, '1'), (17, '17'), (19, '19'), (7, '7'), (11, '11'), (20, '20'), (8, '8'), (13, '13'), (9, '9'), (14, '14'), (2, '2'), (5, '5'), (15, '15'), (4, '4')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Royal', 'Royal'), ('Economy', 'Economy')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='train_name',
            field=models.CharField(blank=True, choices=[('Chattala Express', 'Chattala Express'), ('Banglabandha Express', 'Banglabandha Express'), ('Pabna Express', 'Pabna Express')], default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='trip_no',
            field=models.IntegerField(default=1000000),
        ),
    ]
